name: Check PEP8 and PEP20

on:
  push:
    branches: [ main, develop ]  # Запуск на пушах в эти ветки
  pull_request:
    branches: [ main, develop ]  # Запуск на PR в эти ветки

jobs:
  lint:
    name: Linting with flake8 and PEP20 check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Можно изменить версию

      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip  
          pip install flake8 pycodestyle_magic  

      - name: Run PEP8 check with flake8
        run: flake8 . --count --max-line-length=79 --show-source --statistics

      - name: Run PEP20 check
        run: |  
          echo "Checking PEP20..."  
          python -c "import this" | diff - <(echo 'The Zen of Python, by Tim Peters'; cat) || (echo 'PEP20 philosophy mismatch detected!' && exit 1)ngth: "120"
